
public enum ParsableData
{
    VolMeanRadius,                  // "Vol.MeanRadius(km)"
    Mass,                           // "Massx10^24(kg)"
    EquatorialRadius,               // "Equ.radius,km"  
    PolarAxis,                      // "Polaraxis,km"
    AtmosMass,                      // "Atmos"
    Flattening,                       // "Flattening"
    Oceans,                           // "oceans"
    Density,                    // "Density,g/cm^3"
    Crust,                            // "crust"
    J2_IERS2010,                      // "J2(IERS2010)"
    Mantle,                           // "mantle"
    Surface_G_Polar,                   // "g_p,m/s^2(polar)"

    Outercore,                        // "outercore"
    Surface_G_Equatorial,              // "g_e,m/s^2(equatorial)"
    Innercore,                        // "innercore"
    Standard_G,                         // "g_o,m/s^2"
    FluidcoreRad,                     // "Fluidcorerad"
    Geocentric_G,                        // "GM,km^3/s^2"
    InnercoreRad,                     // "Innercorerad"
    Geocentric_G_1Sig,                  // "GM1-sigma,km^3/s^2"
    EscapeVelocity,                   // "Escapevelocity"
    RotationRate,                    // "Rot.Rate(rad/s)"

    MeanSiderealDay,                // "Meansiderealdy,hr"
    Land,                           // "land,km"
    Sea,                            // "sea,km"
    MeanSolarDay2000,               // "Meansolarday2000,s"
    MeanSolarDay1820,               // "Meansolarday1820,s"

    LoveNo,                        // "Loveno.,k2"
    MomentofInertia,                  // "Momentofinertia"
    AtmosPressure,                   // "Atm.pressure"
    MeanSurfaceTemp_TS,             // "Meansurfacetemp(Ts),K"
    Volume,                       // "Volume,km^3"
    MeanEffectTemp_TE,              // "Meaneffect.temp(Te),K"
    MagneticMoment,                   // "Magneticmoment"
    GeometricAlbedo,                  // "Geometricalbedo"
    VisMag,                     // "Vis.mag,V(1,0)"
    SolarConstant,               // "SolarConstant(W/m^2)"

    ObliquityToOrbit,             // "Obliquitytoorbit,deg"
    SiderealOrbPeriod,            // "Siderealorbperiod"
    OrbitalSpeed,                // "Orbitalspeed,km/s"
    MeanDailyMotion,          // "Meandailymotion,deg/d"
    HillsSphereRadius,                // "Hill'ssphereradius"

    TargetBodyName,                   // "Targetbodyname"
    TargetBodyID,                     // "Targetbodyname(targetbodyID)"
    CenterBodyName,                   // "Centerbodyname"
    CenterBodyID,                     // "Centerbodyname(centerbodyID)"
    CenterSiteName,                   // "Center-sitename"
    StartTime,                        // "Starttime"
    StopTime,                         // "Stoptime"
    StepSize,                         // "Step-size"

    CenterGeodetic,                   // "Centergeodetic"
    CenterCylindric,                  // "Centercylindric"
    CenterRadii,                      // "Centerradii"
    OutputUnits,                      // "Outputunits"
    CalendarMode,                     // "Calendarmode"
    OutputType,                       // "Outputtype"
    OutputFormat,                     // "Outputformat"
    ReferenceFrame                    // "Referenceframe"
}
