
public enum ParsableData
{
    VolMeanRadius_KM,                  // "Vol.MeanRadius(km)"
    Mass_KG,                           // "Massx10^24(kg)"
    EquatorialRadius_KM,               // "Equ.radius,km"  
    PolarAxis_KM,                      // "Polaraxis,km"
    AtmosMass_KG,                      // "Atmos"
    Flattening,                       // "Flattening"
    Oceans,                           // "oceans"
    Density_G_CM3,                    // "Density,g/cm^3"
    Crust,                            // "crust"
    J2_IERS2010,                      // "J2(IERS2010)"
    Mantle,                           // "mantle"
    G_P_M_S2_Polar,                   // "g_p,m/s^2(polar)"

    Outercore,                        // "outercore"
    G_E_M_S2_Equatorial,              // "g_e,m/s^2(equatorial)"
    Innercore,                        // "innercore"
    G_O_M_s2,                         // "g_o,m/s^2"
    FluidcoreRad,                     // "Fluidcorerad"
    GM_KM3_S2,                        // "GM,km^3/s^2"
    InnercoreRad,                     // "Innercorerad"
    GM1Sigma_KM3_S2,                  // "GM1-sigma,km^3/s^2"
    EscapeVelocity_KM_S,                   // "Escapevelocity"
    RotRate_Rad_S,                    // "Rot.Rate(rad/s)"

    MeansideRealDY_HR,                // "Meansiderealdy,hr"
    Land_KM,                           // "land,km"
    Sea_KM,                            // "sea,km"
    MeanSolarDay2000_S,               // "Meansolarday2000,s"
    MeanSolarDay1820_S,               // "Meansolarday1820,s"

    Loveno_K2,                        // "Loveno.,k2"
    MomentofInertia,                  // "Momentofinertia"
    AtmPressure_BAR,                   // "Atm.pressure"
    Meansurfacetemp_TS_K,             // "Meansurfacetemp(Ts),K"
    Volume_KM3,                       // "Volume,km^3"
    MeaneffectTemp_TE_K,              // "Meaneffect.temp(Te),K"
    MagneticMoment,                   // "Magneticmoment"
    GeometricAlbedo,                  // "Geometricalbedo"
    VisMag_V_1_0,                     // "Vis.mag,V(1,0)"
    SolarConstant_W_M2,               // "SolarConstant(W/m^2)"

    ObliquityToOrbit_DEG,             // "Obliquitytoorbit,deg"
    SiderealOrbPeriod_DAY,            // "Siderealorbperiod"
    OrbitalSpeed_KM_S,                // "Orbitalspeed,km/s"
    MeanDailyMotion_DEG_DAY,          // "Meandailymotion,deg/d"
    HillsSphereRadius,                // "Hill'ssphereradius"

    TargetBodyName,                   // "Targetbodyname"
    TargetBodyID,                     // "Targetbodyname(targetbodyID)"
    CenterBodyName,                   // "Centerbodyname"
    CenterBodyID,                     // "Centerbodyname(centerbodyID)"
    CenterSiteName,                   // "Center-sitename"
    StartTime,                        // "Starttime"
    StopTime,                         // "Stoptime"
    StepSize,                         // "Step-size"

    CenterGeodetic,                   // "Centergeodetic"
    CenterCylindric,                  // "Centercylindric"
    CenterRadii,                      // "Centerradii"
    OutputUnits,                      // "Outputunits"
    CalendarMode,                     // "Calendarmode"
    OutputType,                       // "Outputtype"
    OutputFormat,                     // "Outputformat"
    ReferenceFrame                    // "Referenceframe"
}
